-- Run in the Supabase SQL editor before enabling cloud sync.
-- Review RLS policies for the deployment model before applying them.

create table if not exists public.trades (
    id text primary key,
    timestamp timestamptz not null,
    ticker text not null,
    action text not null,
    price double precision not null,
    quantity double precision not null,
    pnl double precision,
    pnl_pct double precision,
    status text default 'open',
    strategy text,
    confidence double precision,
    regime text,
    stop_loss double precision,
    take_profit double precision,
    entry_features jsonb,
    exit_features jsonb,
    closed_at timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.portfolio_snapshots (
    id bigint generated by default as identity primary key,
    date date unique not null,
    cash double precision not null,
    positions_value double precision not null,
    total_value double precision not null,
    daily_return double precision,
    cumulative_return double precision,
    drawdown double precision,
    num_positions integer,
    sharpe_30d double precision,
    created_at timestamptz default now()
);

create table if not exists public.learning_log (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    trigger text not null,
    parameter text not null,
    old_value double precision,
    new_value double precision,
    reason text,
    trades_analyzed integer,
    sharpe_before double precision,
    sharpe_after double precision
);

create table if not exists public.basket_weights (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    weights jsonb not null,
    accuracy double precision,
    trigger text,
    baskets_analyzed integer
);

create table if not exists public.daily_pnl (
    date date primary key,
    pnl double precision,
    pnl_pct double precision,
    equity double precision,
    created_at timestamptz default now()
);

create index if not exists trades_timestamp_idx on public.trades (timestamp);
create index if not exists trades_status_idx on public.trades (status);
